### ISSUE TITLE
Review trading signals code, for all indicators.

### ISSUE THREAD

**Issue by vsaveris** [vsaveris/trading-technical-indicators#2]
Tasks:
- Review trading signals code against Trading Analysis theory and modify whenever necessary.
- Run trading simulation for validation.
- Execute regression testing after each modification.

The task is targeting planned release: **0.2 stable-release (01-01-2021)**

**Task Status:**
- [x] Accumulation Distribution Line
- [x] Average True Range
- [x] Bollinger Bands
- [x] Chaikin Money Flow
- [x] Chaikin Oscillator
- [x] Chande Momentum Oscillator
- [x] Commodity Channel Index
- [x] Detrended Price Oscillator
- [x] Directional Movement Index
- [x] Double Exponential Moving Average
- [x] Ease Of Movement
- [x] Envelopes
- [x] Fibonacci Retracement
- [x] Forecast Oscillator
- [x] Ichimoku Cloud
- [x] Intraday Movement Index
- [x] Klinger Oscillator
- [x] Linear Regression Indicator
- [x] Linear Regression Slope
- [x] Market Facilitation Index
- [x] Mass Index
- [x] Median Price
- [x] Momentum
- [x] Exponential Moving Average
- [x] Simple Moving Average
- [x] Time-Series Moving Average
- [x] Triangular Moving Average
- [x] Variable Moving Average
- [x] Moving Average Convergence Divergence
- [x] Negative Volume Index
- [x] On Balance Volume
- [x] Parabolic SAR
- [x] Performance
- [x] Positive Volume Index
- [x] Price And Volume Trend
- [x] Price Channel
- [x] Price Oscillator
- [x] Price Rate Of Change
- [x] Projection Bands
- [x] Projection Oscillator
- [x] Qstick
- [x] Range Indicator
- [x] Relative Momentum Index
- [x] Relative Strength Index
- [x] Relative Volatility Index
- [x] Standard Deviation
- [x] Stochastic Momentum Index
- [x] Fast Stochastic Oscillator
- [x] Slow Stochastic Oscillator
- [x] Swing Index
- [x] Time Series Forecast
- [x] Triple Exponential Moving Average
- [x] Typical Price
- [x] Ultimate Oscillator
- [x] Vertical Horizontal Filter
- [x] Volatility Chaikins
- [x] Volume Oscillator
- [x] Volume Rate Of Change
- [x] Weighted Close
- [x] Wilders Smoothing
- [x] Williams Accumulation Distribution
- [x] Williams %R

**Comment by vsaveris** [comment]
AccumulationDistributionLine indicator reviewed:

```
Trading Simulation for the <class 'tti.indicators._accumulation_distribution_line.AccumulationDistributionLine'> with arguments {}

Trading Simulation for technical indicator:  AccumulationDistributionLine

- Simulation executed in : 8.98 seconds.

- Simulation Statistics:
	number_of_trading_days: 5651
	number_of_buy_signals: 4767
	number_of_ignored_buy_signals: 0
	number_of_sell_signals: 601
	number_of_ignored_sell_signals: 0
	last_stock_value: 475.5
	last_exposure: 22340.73
	last_open_long_positions: 40
	last_open_short_positions: 0
	last_portfolio_value: 19020.0
	last_earnings: 19817.21
	final_balance: 38837.21

**Comment by vsaveris** [comment]
AverageTrueRange reviewed:"

```
Trading Simulation for the <class 'tti.indicators._average_true_range.AverageTrueRange'> with arguments {}

Trading Simulation for technical indicator:  AverageTrueRange

- Simulation executed in : 16.07 seconds.

- Simulation Statistics:
	number_of_trading_days: 5651
	number_of_buy_signals: 4690
	number_of_ignored_buy_signals: 0
	number_of_sell_signals: 929
	number_of_ignored_sell_signals: 0
	last_stock_value: 475.5
	last_exposure: 26276.79
	last_open_long_positions: 36
	last_open_short_positions: 11
	last_portfolio_value: 11887.5
	last_earnings: 20898.22
	final_balance: 32785.72

**Comment by vsaveris** [comment]
BollingerBands reviewed:

```
Trading Simulation for the <class 'tti.indicators._bollinger_bands.BollingerBands'> with arguments {'period': 50, 'std_number': 2.5}

Trading Simulation for technical indicator:  BollingerBands

- Simulation executed in : 9.34 seconds.

- Simulation Statistics:
	number_of_trading_days: 5651
	number_of_buy_signals: 114
	number_of_ignored_buy_signals: 0
	number_of_sell_signals: 124
	number_of_ignored_sell_signals: 0
	last_stock_value: 475.5
	last_exposure: 0.0
	last_open_long_positions: 0
	last_open_short_positions: 0
	last_portfolio_value: 0.0
	last_earnings: 1190.42
	final_balance: 1190.42

**Comment by vsaveris** [comment]
ChaikinMoneyFlow reviewed 

```Trading Simulation for the <class 'tti.indicators._chaikin_money_flow.ChaikinMoneyFlow'> with arguments {'period': 14}

Trading Simulation for technical indicator:  ChaikinMoneyFlow

- Simulation executed in : 10.56 seconds.

- Simulation Statistics:
	number_of_trading_days: 5651
	number_of_buy_signals: 582
	number_of_ignored_buy_signals: 0
	number_of_sell_signals: 616
	number_of_ignored_sell_signals: 0
	last_stock_value: 475.5
	last_exposure: 4414.7
	last_open_long_positions: 5
	last_open_short_positions: 3
	last_portfolio_value: 951.0
	last_earnings: 4266.14
	final_balance: 5217.14

**Comment by vsaveris** [comment]
ChaikinOscillator reviewed.

```Trading Simulation for the <class 'tti.indicators._chaikin_oscillator.ChaikinOscillator'> with arguments {}

Trading Simulation for technical indicator:  ChaikinOscillator

- Simulation executed in : 11.27 seconds.

- Simulation Statistics:
	number_of_trading_days: 5651
	number_of_buy_signals: 374
	number_of_ignored_buy_signals: 0
	number_of_sell_signals: 464
	number_of_ignored_sell_signals: 0
	last_stock_value: 475.5
	last_exposure: 7723.62
	last_open_long_positions: 8
	last_open_short_positions: 5
	last_portfolio_value: 1426.5
	last_earnings: 2922.97
	final_balance: 4349.47
